const URL = 'https://data.sfgov.org/resource/bbb8-hzi6.json';
const APP_TOKEN = 'h4xtLlQaSmrhoIdORaP9EbvtV';
const LIMIT = 10;
const ORDER_BY = 'applicant';
const COMMAND_NEXT = 'next';
const COMMAND_EXIT = 'exit';
const MESSAGE_APP_STOPPED = 'APPLICATION STOPPED';
const MESSAGE_INVALID_COMMAND = 'YOU ENTERED INVALID COMMAND';
const MESSAGE_FINISHED = 'FINISHED';
const STATUS_OK = 200;

module.exports = {
    URL: URL,
    APP_TOKEN: APP_TOKEN,
    LIMIT: LIMIT,
    ORDER_BY: ORDER_BY,
    COMMAND_NEXT: COMMAND_NEXT,
    COMMAND_EXIT: COMMAND_EXIT,
    MESSAGE_APP_STOPPED: MESSAGE_APP_STOPPED,
    MESSAGE_INVALID_COMMAND: MESSAGE_INVALID_COMMAND,
    STATUS_OK: STATUS_OK,
    MESSAGE_FINISHED: MESSAGE_FINISHED
};
